### ISSUE TITLE
客户端一直显示端口被占用,响应码为424,怎么解决

### ISSUE THREAD

**Issue by perfectlxy** [khvysofq/proxyer#4]
服务端安装完成,客户端浏览器访问127.0.0.1:9876,到配置内网穿透设置这一步,设置完成提交,一直显示端口被占用,响应码为424,怎么解决

**Comment by onlunar** [comment]
docker-compose down
docker-compose up -d
重起一个proxyer服务，重新下载windows界面端用就行了
估计是服务端没处理端口释放
