### ISSUE TITLE
安装Docker提示镜像已删除

### ISSUE THREAD

**Issue by szlanpa** [khvysofq/proxyer#7]
Pulling install (registry.cn-hangzhou.aliyuncs.com/proxyer/proxyer/proxyer:v1.0.1)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

安装时出现以上提示，提示镜像已被删除

**Comment by sunlin1111** [comment]
镜像已被删除，不维护了吗？ 请作者给个答复

**Comment by fzdwx** [comment]
https://github.com/fzdwx/burst 老哥们，我也整了一个，欢迎使用！
